/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.pkg2;

import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/Icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonProductor = new javax.swing.JButton();
        jButtonConsumidor = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        abajo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        arriba = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bufer de datos", "Productor", "Consumidor", "Semaforo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 330));

        jButtonProductor.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProductor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonProductor.setForeground(new java.awt.Color(153, 0, 0));
        jButtonProductor.setText("Iniciar");
        jButtonProductor.setBorderPainted(false);
        getContentPane().add(jButtonProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jButtonConsumidor.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConsumidor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonConsumidor.setForeground(new java.awt.Color(153, 0, 0));
        jButtonConsumidor.setText("Iniciar");
        jButtonConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsumidorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsumidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jButtonIniciar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(153, 0, 0));
        jButtonIniciar.setText("Iniciar");
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        abajo.setFont(new java.awt.Font("Symbol", 0, 11)); // NOI18N
        abajo.setForeground(new java.awt.Color(255, 255, 255));
        abajo.setText("ppppppppppppppppppppppppppppppppppppppppppppppppppl4pppppppppppppppppppppppp");
        getContentPane().add(abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consumidor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Productor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));

        arriba.setFont(new java.awt.Font("Symbol", 0, 11)); // NOI18N
        arriba.setForeground(new java.awt.Color(255, 255, 255));
        arriba.setText("ppppppppppppppppppppppppppppppppppppppppppppppppppl4pppppppppppppppppppppppp");
        getContentPane().add(arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/47d3a2541523fee1a98776041809b272.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsumidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsumidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel abajo;
    private javax.swing.JLabel arriba;
    private javax.swing.JButton jButtonConsumidor;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonProductor;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
